version: '3.7'
services:
  backend:
    build:
      context: ./server
      dockerfile: DockerProd.Dockerfile
  nginx:
    restart: always
    build:
      context: ./docker/nginx
    ports:
      - '81:80'
    networks:
      - racroishop
