version: '3.7'
services:
  postgres:
    image: postgres:alpine
    env_file: ./server/.env
    ports:
      - '5432:5432'
    volumes:
      - ./server/pgdata:/var/lib/postgresql/data
    networks:
      - racroishop
  backend:
    env_file: ./server/.env
    build:
      context: ./server
      # args:
      #   TEN_BIEN: ${GIA_TRI_BIEN}(có thể lấy trong file .env)
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    networks:
      - racroishop
  # frontend:
  #   env_file: ./server/.env
  #   build:
  #     context: ./client
  #     args:
  #       BACKEND_HOST_ARG: http://backend:4000/
  #   environment:
  #     BACKEND_HOST: http://backend:4000/
  #     HOST_IP: http://host.docker.internal:4000/
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
  #     - postgres
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - racroishop
  #   volumes:
  #     - ./client/app:/app
volumes:
  db-data:
networks:
  racroishop:
    driver: bridge
