version: 2.1
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@1.7.0
jobs:
  test-build-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
      - node/install-packages:
          app-dir: ~/project/server
          pkg-manager: yarn
          with-cache: true
      - run:
          command: cd server && yarn test
          name: Run YARN tests
      - run:
          command: cd server && yarn build
          name: Run YARN BUILD
  # build-backend:
  #   executor: docker/docker
  #   steps:
  #     - setup_remote_docker:
  #         version: 19.03.13
  #     - checkout
  #     - run: ls
  #     - run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
  #     - store_test_results:
  #         path: test
  build-push-docker:
    environment:
      DOCKER_IMAGE: nguyendangkhuong/racroishop
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/build:
          path: ~/project/server
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
    # steps:
    #   - add_ssh_keys:
    #       fingerprints:
    #         - '5a:30:fa:15:ba:ae:be:9c:9b:9a:61:e5:65:0d:ec:3a'
    #   - run:
    #       name: Access server nha
    #       command: ssh -oStrictHostKeyChecking=no -v root@45.76.160.102 './kienthucthuvi_deploy.sh'
workflows:
  test-backend-hihi:
    jobs:
      - test-build-backend
  build-backend-nha:
    jobs:
      - build-push-docker:
          #  t-build-backend
          filters:
            branches:
              only:
                - config_docker
