version: 2.1
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@1.7.0
jobs:
  test-build-backend:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
      - node/install-packages:
          app-dir: ~/project/server
          pkg-manager: yarn
          with-cache: true
      - run:
          command: cd server && yarn test
          name: Run YARN tests
      - run:
          command: cd server && yarn build
          name: Run YARN BUILD
  # test-build-frontend:
  #   executor:
  #     name: node/default
  #   steps:
  #     - checkout
  #     - node/install:
  #         lts: true
  #         install-npm: false
  #     - node/install-packages:
  #         app-dir: ~/project/server
  #         pkg-manager: yarn
  #         with-cache: true
  #     - run:
  #         command: cd server && yarn test
  #         name: Run YARN tests
  #     - run:
  #         command: cd server && yarn build
  #         name: Run YARN BUILD
  deploy-backend:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - '5a:30:fa:15:ba:ae:be:9c:9b:9a:61:e5:65:0d:ec:3a'
      - run:
          name: Access server nha
          command: ssh -oStrictHostKeyChecking=no -v root@45.76.160.102 './racroishop_deploy.sh'
workflows:
  test-backend-hihi:
    jobs:
      - test-build-backend
  build-backend-nha:
    jobs:
      - deploy-backend:
          filters:
            branches:
              only:
                - config_docker
