version: '3.7'
services:
  postgres:
    image: postgres:alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  racroishop:
    env_file: .env
    # build:
    # context: .
    # args:
    #   TEN_BIEN: ${GIA_TRI_BIEN}(có thể lấy trong file .env)
    restart: unless-stopped
    depends_on:
      - postgres
      - nginx
    ports:
      - '4000:4000'
volumes:
  db-data:
