version: '3.7'
services:
  postgres:
    image: postgres
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  racroishop:
    env_file: .env
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '4000:4000'
volumes:
  db-data:
